recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model_name: gpt-4o-mini

policies:
- name: FlowPolicy
#  - name: EnterpriseSearchPolicy
#  - name: RulePolicy
  
assistant_id: 20241104-203001-bounded-triathlon
